version: "3.8"

networks:
  web_server:
  database:

services:
  redis:
    container_name: redis
    image: redis:alpine3.16
    restart: always
    volumes:
      - "./redis/data:/data"
    ports:
      - "6379:6379"
    networks:
      - database

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "9907:27017"
    networks:
      - database

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "9000:8081"
    depends_on:
      - mongo
    networks:
      - database

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    command: mysqld --sql_mode="ALLOW_INVALID_DATES"
    volumes:
      - "./mariadb/data:/var/lib/mysql"
    ports:
      - "9906:3306"
    networks:
      - database

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - database

  php:
    container_name: php7.4.30
    build: "./php7.4.30/"
    restart: always
    volumes:
      - "./apache2.4.54/htdocs/:/usr/local/apache2/htdocs/"
    networks:
      - web_server
      - database

  apache2.4.54:
    container_name: apache2.4.54
    build: "./apache2.4.54/"
    restart: always
    volumes:
      - "./apache2.4.54/htdocs/:/usr/local/apache2/htdocs/"
    ports:
      - "8001:80"
    depends_on:
      - php
      - mariadb
    networks:
      - web_server
      - database
